WIP SBW-27675 add payment
Seitenbau/Amt24-Blaupauseprozess pull request #3
Opened 2023-10-30 13:11 UTC by Nijin22

Do not commit yet. Await release

2023-11-03 13:56 UTC, Nijin22 commented
@sweipert96 Ready for review :) (Aber bitte noch nicht mergen. Das machen wir dann erst, wenn die Sächsische Staatskanzlei das OK gibt. Die Review können wir aber wahrscheinlich jetzt schon machen :) )

2023-11-06 07:40 UTC, sweipert96 requested changes
Nur ein paar kleine textuelle Sachen ;)

2023-11-06 07:40 UTC, sweipert96 commented on Changelog.md
> +- Für einen Prozess kann die Bezahlung aktiviert.
"Für einen Prozess kann die Bezahlung aktiviert werden."

2023-11-06 07:40 UTC, sweipert96 commented on Changelog.md
> +  - So erstelle Prozesse verfügen über die neuen Prozessparameter `ePayBL-keystore`, `ePayBL-keystorePassword`, `ePayBL-mandant`, `ePayBL-bewirtschafter`, `ePayBL-haushaltsstelle`, `ePayBL-objektnumm
"So erstellte"

2023-11-06 07:40 UTC, sweipert96 commented on README.md
> +Bearbeiten-Symbol (2). Die meisten der Parameter sind ePayBL-Parameter, also solche welche verwendet werden, um Ihr
"also solche welche" ist IMO keine einfache Sprache 🙈 einfacher zu verstehen wäre vllt: "Die meisten der Parameter sind ePayBL-Parameter - dies sind Parameter, die verwendet werden, um Ihr..."

2023-11-07 08:30 UTC, sweipert96 approved these changes

2023-11-20 07:32 UTC, sweipert96 approved these changes

2023-11-28 11:56 UTC, merged